export const SAVE_MEDICINE='SAVE_MEDICINE';
export const SAVE_MEDICINE_IMAGE='SAVE_MEDICINE_IMAGE';
export const FETCH_ALL_MEDICINES='FETCH_ALL_MEDICINES';
export const FETCH_MEDICINE_BY_ID='FETCH_MEDICINE_BY_ID';
export const FETCH_MEDICINE_BY_PATTERN='FETCH_MEDICINE_BY_PATTERN'